{
    "name": "EcoSphere ESG Management",
    "summary": "Environmental, social and governance management for Odoo",
    "version": "1.0.0",
    "category": "Sustainability",
    "author": "EcoSphere",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr", "product", "purchase"],
    "data": [
        "security/esg_security.xml",
        "security/ir.model.access.csv",
        "data/esg_data.xml",
        "views/esg_department_views.xml",
        "views/esg_environmental_views.xml",
        "views/esg_purchase_views.xml",
        "views/esg_social_views.xml",
        "views/esg_governance_views.xml",
        "views/esg_gamification_views.xml",
        "views/esg_reports_views.xml",
        "views/esg_settings_views.xml",
        "wizard/esg_report_builder_views.xml",
        "views/esg_menus.xml",
        "reports/environmental_report_template.xml",
        "reports/social_report_template.xml",
        "reports/governance_report_template.xml",
        "reports/esg_summary_report_template.xml",
    ],
    "application": True,
    "installable": True,
}
